//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiWebClientes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.Pedido = new HashSet<Pedido>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string RazonSocial { get; set; }
        public string CIF_NIF { get; set; }
        public string Telefono { get; set; }
        public string Email { get; set; }
        public bool Activo { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public string Direccion_Direccion1 { get; set; }
        public string Direccion_Direccion2 { get; set; }
        public string Direccion_Pais { get; set; }
        public string Direccion_Provincia { get; set; }
        public string Direccion_Ciudad { get; set; }
        public string Direccion_CodigoPostal { get; set; }
        public string DireccionFacturacion_Direccion1 { get; set; }
        public string DireccionFacturacion_Direccion2 { get; set; }
        public string DireccionFacturacion_Pais { get; set; }
        public string DireccionFacturacion_Provincia { get; set; }
        public string DireccionFacturacion_Ciudad { get; set; }
        public string DireccionFacturacion_CodigoPostal { get; set; }
        public bool EsCliente { get; set; }
        public bool EsProveedor { get; set; }
        public string Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pedido> Pedido { get; set; }
    }
}
